homepage/homepage/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'admin/password_reset/',
        auth_views.PasswordResetView.as_view(),
        name='admin_password_reset',
    ),
    path('admin/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done',
         ),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm',
         ),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete',
         ),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('portfolio.urls')),
]

homepage/portfolio/urls.py
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'portfolio'

urlpatterns = [
    path('lang', views.set_language, name='set-lang'),
    re_path(r'^contact(?:/(?P<slug>[\w|-]{0,}))?',
            views.ContactView.as_view(), name="contact"),
    re_path(r'^(?!(admin|media|static))(?P<section_slug>[\w|-]+)/(?P<collectionitem_slug>[\w|-]+)',
            views.DetailView.as_view(), name='detail'),
    re_path(r'^(?!(admin|media|privacy|imprint]))(?P<section_slug>[\w|-]+$)',
            views.CollectionView.as_view(), name='collection'),
    re_path(r'^(?!(admin|media|static|projects|photography))(?P<page_name>[\w|-]{0,}$)',
            views.PageView.as_view(), name='page'),
]


if settings.ENVIRONMENT == 'development':

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    print(settings.STATIC_URL, settings.MEDIA_URL)
    print(settings.STATIC_ROOT, settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

homepage/portfolio/forms.py
from django.forms import ModelForm, ValidationError
from django.forms.widgets import TextInput

from .models import *


class IconForm(ModelForm):
    class Meta:
        model = Icon
        fields = '__all__'
        widgets = {
            'colour': TextInput(attrs={'type': 'color'}),
        }

homepage/portfolio/views.py
import logging
from importlib import import_module

from django.conf import settings
from django.core.exceptions import *
from django.db.models import Q
from django.http import Http404, HttpResponse, HttpResponseRedirect, QueryDict
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.urls import reverse
from django.utils import translation
from django.views import generic
from django.views.generic.base import ContextMixin
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.list import MultipleObjectMixin

from .models import *
from .tokens import account_activation_token
from .translations import filter_translations


SessionStore = import_module(settings.SESSION_ENGINE).SessionStore
s = SessionStore()

logger = logging.getLogger(__name__)

"""
Base Context, providing navigation and footer links for all pages.
"""


class BaseContext(ContextMixin):
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        lang = translation.get_language()

        navlinks = NavLink.objects.select_related('page').order_by(
            'position'
        )
        pages = Page.objects.all().select_related('common')
        pages = filter_translations(
            pages, lang).order_by('common__footer_position')

        context['sociallinks'] = SocialLink.objects.all()
        context['pages'] = pages
        context['navlinks'] = navlinks
        context['footerlinks'] = FooterLink.objects.order_by('position')

        return context


"""
Generic Views for Page, Collection, and Detail pages.
#####################################################

Page View consists of Sections defined in the database.
(model: Page, PageCommon)

Collection View consists of list view of Collection Items, also defined in the
database (model: CollectionItem, CollectionItemCommon)

Detail View consists of a single Collection Item

"""

"""TODO: access args from url conf instead of parsing path"""


class PageView(BaseContext, generic.ListView):
    model = Section
    context_object_name = 'sections'

    template_name = 'portfolio/page.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        lang = translation.get_language()

        sections = self.get_queryset().values_list('common__id')

        queryset = CollectionItem.objects.select_related('common').filter(
            common__isnull=False,
            common__parent_section__id__in=sections
        )

        queryset = filter_translations(queryset, lang)

        context['collectionitems'] = queryset

        spotlights = CollectionItem.objects.filter(
            common__spotlight=True).select_related(
                'common__parent_section').prefetch_related(
                    'common__parent_section__sections').filter(
                        common__parent_section__id__in=sections)

        context['spotlights'] = filter_translations(spotlights, lang)

        return context

    def get_queryset(self):

        lang = translation.get_language()

        page_slug = self.request.path.replace('/', '')

        if page_slug == '':

            page_slug = 'home'

        page = Page.objects.filter(lang=lang, slug=page_slug)
        if len(page) == 0:
            page = Page.objects.filter(
                lang=settings.LANGUAGE_CODE, slug=page_slug)
        page = page.first()
        queryset = Section.objects.select_related(
            'common').filter(common__page__id=page.common.id)

        queryset = filter_translations(
            queryset, lang).order_by('common__position')

        return queryset


class CollectionView(BaseContext, generic.ListView):
    model = CollectionItem
    context_object_name = 'collectionitems'

    template_name = 'portfolio/page_collection.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        lang = translation.get_language()

        path = self.request.path.split('/')
        section_slug = path[1]

        section = Section.objects.filter(lang=lang, slug=section_slug)
        if len(section) == 0:
            section = Section.objects.filter(
                lang=settings.LANGUAGE_CODE, slug=section_slug)

        context['section'] = section.first()

        return context

    def get_queryset(self):

        lang = translation.get_language()

        # Instead of parsing url, can we access slug directly?
        page_slug = self.request.path.replace('/', '')

        section = Section.objects.filter(
            lang=lang, slug=page_slug)
        if len(section) == 0:
            section = Section.objects.filter(
                lang=settings.LANGUAGE_CODE, slug=page_slug)

        section = section.first()

        queryset = CollectionItem.objects.select_related(
            'common').filter(common__parent_section__id=section.common.id)

        queryset = filter_translations(queryset, lang)

        return queryset


class DetailView(BaseContext, generic.ListView):
    model = CollectionItem
    template_name = 'portfolio/page_detail.html'
    context_object_name = 'collectionitem'

    def get_queryset(self):
        lang = translation.get_language()

        path = self.request.path.split('/')
        item_slug = path[2]

        queryset = CollectionItem.objects.filter(
            slug=item_slug)

        queryset = filter_translations(queryset, lang)
        queryset = queryset.first()
        return queryset


class BaseTemplateView(BaseContext, generic.TemplateView):
    pass


"""
Contact view, for contact form actions and email confirmation.

"""


class ContactView(BaseContext, generic.View):
    model = ContactResponse
    context_object_name = 'contactresponses'
    template_name = 'portfolio/contact.html'

    def get(self, request, *args, **kwargs):

        context = self.get_context_data(kwargs=kwargs)

        lang = translation.get_language()

        response_slug = kwargs['slug']
        contact_id = self.request.GET.get('id')
        token = self.request.GET.get('token')
        if len(response_slug) > 0:
            queryset = ContactResponse.objects.filter(
                slug=response_slug)

            context['contactresponse'] = filter_translations(
                queryset, lang).first()

            if response_slug == 'confirmed' or response_slug == 'thanks':
                context['messages'] = Message.objects.filter(
                    contact__id=contact_id, sent=False)

        if contact_id:
            contact = get_object_or_404(Contact, id=contact_id)

        """
        Redirects for email confirmation and resend confirmation email
        """
        # Confirm email address and redirect to contact/confirmed
        if response_slug == 'confirm' and contact_id and token:
            if account_activation_token.check_token(contact, token):
                contact.email_confirmed = True
                contact.save()
                messages = Message.objects.filter(contact=contact, sent=False)
                for message in messages:
                    message.send()
                url = reverse('portfolio:contact', args=['confirmed'])
                return HttpResponseRedirect(f"{url}?{QueryDict(f'id={contact.id}').urlencode()}")
            else:
                raise Http404('Invalid user/token combination')

        # Catch missing contact or token params
        elif response_slug == 'confirm' and (not contact_id or not token):
            raise Http404('Missing user or token parameters')

        # raise 404 on other urls
        elif response_slug not in [
                'confirmed',
                'thanks',
                'messages',
                'unconfirmed',
                'send-confirmation-email',
                'sent-confirmation-email']:
            raise Http404('Contact view not found')

        # Finally, render template with context
        return render(request, 'portfolio/contact.html', context=context)

    def post(self, request, *args, **kwargs):

        try:
            response_slug = kwargs['slug']
        except KeyError:
            response_slug = ''

        if response_slug == '':
            name = request.POST['name']
            email = request.POST['email']
            subject = request.POST['subject']
            content = request.POST['message']
            try:
                contact = Contact.objects.get(email_address=email)
            except Contact.DoesNotExist:
                contact = Contact(email_address=email, name=name)
                contact.save()
                token = account_activation_token.make_token(contact)
                contact.send_confirmation_email(token)

            # try:

            message = Message(
                contact=contact,
                subject=subject,
                content=content)

            message.save()

            if message.contact.email_confirmed:
                message.send()
                url = reverse('portfolio:contact', args=['thanks'])
                return HttpResponseRedirect(f"{url}?{QueryDict(f'id={contact.id}').urlencode()}")

            else:
                url = reverse('portfolio:contact', args=['unconfirmed'])
                return HttpResponseRedirect(f"{url}?{QueryDict(f'id={contact.id}').urlencode()}")

        elif response_slug == 'send-confirmation-email':
            email = request.POST['email']

            contact = Contact.objects.get(email_address=email)
            token = account_activation_token.make_token(contact)
            contact.send_confirmation_email(token)

            return HttpResponseRedirect(reverse('portfolio:contact', args=['sent-confirmation-email']))

    def delete(self, request, *args, **kwargs):
        """Delete all contact's information"""
        pass

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        contact_id = self.request.GET.get('id')

homepage/portfolio/templates/portfolio/base_email.html
<!DOCTYPE html>

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_language_info for LANGUAGE_CODE as lang %}

{% load inlinecss %}
{% inlinecss "portfolio/email.css" %}

<html lang="{{ LANGUAGE_CODE }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link rel="shortcut icon" type="image/png" href="{{MEDIA_URL}}/favicon.ico" />
    <title>{% block title %}Fabian Volkers{% endblock title %}</title>
    <meta name="description" content="{% block description %}Fabian Volkers' Portfolio{% endblock description %}">
    <meta name="author" content="Fabian Volkers">
{% comment %}     <style>
        body {
            margin: 0;
            display: grid;
            grid-template-rows: auto 1fr auto;
            row-gap: 20px;
            min-height: 100vh;
            font-family: Montserrat, sans-serif;
        }

        h1,
        h2,
        h4 {
            font-weight: 400;
        }

        nav {
            max-width: 1720px;
            margin: 0 auto;

            display: grid;
            grid-template-columns: 1fr auto 1fr;
        }

        nav a {
            color: white;
            text-decoration: none;
            text-transform: uppercase;
            transition: .3s all ease-in-out;
        }

        nav a:hover {
            opacity: .7;
        }

        nav a:visited {
            color: white;
        }

        .nav-container {
            width: 100%;
            background-color: black;
            grid-row: 1;
        }

        .nav-container i {
            color: white;
            font-size: 50px;
        }


        .logo {
            grid-column: 2;
            font-size: 40px;
            padding: 1rem;
        }

        #content {
            display: grid;
            padding: 15vh 10vw;
            grid-row: 2;


        }

        #content a {
            text-decoration: none;
        }

        #content a:hover {
            text-decoration: underline;
        }

        #content a:visited {
            color: black;
        }




        footer {
            width: 100%;
            margin: 0 auto;
            background-color: black;
            color: white;
            display: grid;
            grid-template-columns: 1fr 1fr 1fr;
            grid-row: 3;
            padding-bottom: 20px;

        }

        footer h4 {
            text-align: left;
            padding-left: 15vw;
            font-size: 20px;
        }

        footer a {
            color: white;
            text-decoration: none;
            transition: .3s all ease-in-out;

        }

        footer a:hover {
            opacity: .7;
        }

        footer a:visited {
            color: white;
        }

        footer ul {
            list-style: none;
            padding-left: 40%;
            padding-inline-start: 15vw;
        }

        footer i {
            padding-right: 10px;
        }

        #footer-left {
            grid-column: 1;
        }

        #footer-right {
            grid-column: 3;
        }


        #footer-center {
            grid-column: 2;
        }



        /************************************************************************************************/
        /************************************************************************************************/
        /************************************************************************************************/
        /************************************************************************************************/
        /************************************************************************************************/
        /************************************************************************************************/


        /** Mobile styles: max 700px **/


        @media only screen and (max-width: 900px) {
            :root {
                --social-circle-a-d: 15vw;
                --social-circle-d: 35vw;
            }

            h1 {
                font-size: 40px;
            }

            h2 {
                font-size: 35px;
            }

            h4 {
                font-size: 25px;
            }

            p {
                font-size: 20px;
            }

            label {
                font-size: 25px;
            }



            .logo {

                font-size: 35px;
                padding: 1rem;
            }

            #content {
                padding: 0 2vw;
            }

            .collection-container {
                grid-template-columns: 1fr;
                column-gap: 5vw;
            }

            .column-2 {
                grid-column: 1;
            }

            .column-3 {
                grid-column: 1;
            }

            .collection-item {
                width: 90%;

            }

            .collection-item img {
                max-width: 80vw;
                z-index: 200;
            }


            #footer-left,
            #footer-right,
            #footer-center {
                grid-column: 1;
                width: 100vw;
                font-size: 20px;

            }

            footer h4 {
                text-align: left;
                padding-left: 10px;
            }

            footer li {
                padding: 10px 0 10px 30px;
            }

        }
    </style> {% endcomment %}
    <!--
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/style.css' %}">
-->
    <script src="https://kit.fontawesome.com/0d7dc3f746.js" crossorigin="anonymous"></script>
</head>

<body>
    {% block navbar %}
    <div class="nav-container">
        <nav>
            <a href="https://fabianvolkers.com" class="logo">Fabian Volkers</a>
        </nav>
    </div>
    {% endblock navbar %}
    <div id='content'>
        {% block content %}
        {% lorem %}
        {% endblock content %}
    </div>
    {% block footer %}
    <footer>
        <div id='footer-left'>
            <h4>Sitemap</h4>
            <ul>
                {% for page in pages %}
                {% if page.common.footer_link == True%}
                <li>
                    <a
                        href="https://fabianvolkers.com{% url page.common.page_type.view_name page.slug %}">{{ page.name }}</a>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div id='footer-center'>
            <h4>Legal</h4>
            <ul>
                <li>
                    <a href="https://fabianvolkers.com{% url 'portfolio:page' 'imprint' %}">Imprint</a>
                </li>
                <li>
                    <a href="https://fabianvolkers.com{% url 'portfolio:page' 'privacy' %}">Privacy</a>
                </li>
            </ul>
        </div>
        <div id='footer-right'>
            <h4>Links</h4>
            <ul>
                {% for link in footerlinks %}
                <li>
                    <a href="{{ link.url }}"><i class="{{ link.icon.icon_class }}"></i>{{ link.name }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </footer>
    {% endblock footer %}
    <script src="{% static 'portfolio/script.js' %}" crossorigin="anonymous"></script>
</body>

</html>
{% endinlinecss %}

homepage/portfolio/templates/portfolio/collection.html
{% extends 'portfolio/base_page.html' %}
{% block title %}{{ section.name }}{% endblock title %}
{% block description %}{{ section.name }}{% endblock description %}

{% block content %}
<h1>{{ section.name }}</h1>
{% include 'portfolio/index_collection.html' with section=section%}
{% endblock content %}

homepage/portfolio/templates/portfolio/confirmed_email.html.jinja2
Thank you for confirming your email address.

homepage/portfolio/templates/portfolio/contact.html
{% extends 'portfolio/base_page.html' %}
{% load i18n %}
{% block content %}
<h3>{{ contactresponse.name }}</h3>
<p>{{ contactresponse.message }}</p>
{{ contactresponse.common.action.name }}
{% if contactresponse.common.action %}
<form action="{% url contactresponse.common.action.page.page_type.view_name contactresponse.common.action.argument %}" method="{{ contactresponse.common.action.method }}">
{% csrf_token %}
<input type='hidden' name='email' id='email' value="{{ contact.email_address }}"></input>
<input type='submit' value="{{ contactresponse.common.action.name }}">
</form>
{% endif %}
{% if messages %}
<h3>{% trans "These messages have been sent" %}</h3>
{% endif %}
{% for message in messages %}
<h4>{{ message.subject }}</h4>
<p>{{ message.content }}</p>
<hr>
{% endfor %}
{% endblock content %}

homepage/portfolio/templates/portfolio/contact.html.jinja2
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Thank you for messaging me</title>
  <meta name="description" content='Thank you for messaging me'>
  <meta name="author" content="Fabian Volkers">

  <link rel="stylesheet" href="css/styles.css?v=1.0">

</head>

<body>
<h1>Thank You for messaging me</h1>
<p>{{ message.email }}</p>
<p>{{ message.subject }}</p>
<p>{{ message.content }}</p>
</body>
</html>

homepage/portfolio/templates/portfolio/contact_email.html.jinja2
{{ from }}
{{ subject }}
{{ message }}

homepage/portfolio/templates/portfolio/detail.html
{% extends 'portfolio/base_page.html' %}
{% block title %}{{ collectionitem.name }}{% endblock title %}
{% block description %}{{ collectionitem.name }}{% endblock description %}

{% block content %}
<h1>{{ collectionitem.name }}</h1>
<img src="{{ MEDIA_URL }}/{{ collectionitem.common.image }}" draggable="false" alt-text="{{ collectionitem.image_alttext }}">
<div>
{% autoescape off %}
{{ collectionitem.description }}
{% endautoescape %}
</div>
{% endblock content %}

homepage/portfolio/templates/portfolio/index.html
{% extends 'portfolio/base_page.html' %}
{% block content %}
{% for section in sections %}
{% if section.slug != 'spotlight' or section.slug == 'spotlight' %}
<section id="{{ section.slug }}" style="grid-row: {{ forloop.counter }}">
    <h2>{{ section.name }}</h2>
    <p>{{ section.description }}</p>
    {% include section.common.section_type.template_name with section=section %}
</section>
{% endif %}
{% endfor %}
{% endblock content %}

homepage/portfolio/templates/portfolio/page_collection.html
{% extends 'portfolio/base_page.html' %}
{% block title %}{{ section.name }}{% endblock title %}
{% block description %}{{ section.name }}{% endblock description %}

{% block content %}
<h1>{{ section.name }}</h1>
{% include section.common.section_type.template_name with section=section%}
{% endblock content %}

homepage/portfolio/templates/portfolio/project.html.jinja2
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>{{ project.name }}</title>
  <meta name="description" content='{{ project.description }}'>
  <meta name="author" content="Fabian Volkers">

  <link rel="stylesheet" href="css/styles.css?v=1.0">

</head>

<body>
<h1>{{ project.name }}</h1>
<p>{{ project.description }}</p>
</body>
</html>

homepage/portfolio/templates/portfolio/section_collection.html
<div class="collection-container">
    {% for item in collectionitems %}
    {% if item.common.parent_section == section.common %}
    <div id="{{ item.slug }}" class="collection-item {% cycle 'column-1' 'column-2' 'column-3' %}">
        <a href="{% url 'portfolio:detail' section.slug item.slug %}">
            <h4>{{ item.name }}</h4>
        </a>
        <div>
            <a href="{% url item.common.detail_view section.detail_slug item.slug %}">
                <img src="{{ MEDIA_URL }}{{ item.common.image }}">
                <span></span>
            </a>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>

homepage/portfolio/templates/portfolio/section_contact.html
{% load i18n %}
<div id="contact-container">
    <div class="contact-section">
        <p>{% trans "Send me a message" %}...</p>
        <form action="{% url 'portfolio:contact' %}" method="post" id='contact-form'>
            {% csrf_token %}
            <label for="name">{% trans "Name" %}</label><br>
            <input type="text" name="name" id="name" placeholder="Ada Lovelace">
            <br>
            <label for="email">{% trans "Email Address" %}</label><br>
            <input type="email" name="email" id="email" placeholder="ada.lovelace@example.com">
            <br>
            <label for="subject">{% trans "Subject" %}</label><br>
            <input type="text" name="subject" id="subject" placeholder="{% trans "Subject" %}">
            <br>
            <label for="message">{% trans "Message" %}</label><br>
            <textarea name="message" id="message" placeholder="{% trans "Enter your message here" %}..." form='contact-form'></textarea>
            <br>


            <input type="submit" value="{% trans "Submit" %}" id="contact-submit">
        </form>
    </div>
    <div class="contact-section" id="circle-section">
        <div class='circle-container'>
        <p class="circle-text">...{% trans "or find me on one of these platforms" %}</p>
            <style>
            {% for sociallink in sociallinks %}
            .{{ sociallink.icon.slug }} {
                background: {{ sociallink.icon.colour_value }};
                color: #FFFFFF;

            }

            .{{ sociallink.icon.slug }}:hover {
                background: #FFFFFF;
                color: {{ sociallink.icon.colour_value }} !important;
            }
            {% endfor %}
            </style>
            {% for sociallink in sociallinks %}
            <a href=" {{ sociallink.external }}" target="_blank" class="{{ sociallink.position }} {{ sociallink.icon.slug }} circle-fa" style="background"><i
                    class="fab {{ sociallink.icon.icon_class }} icon-fa"></i></a>
            {% endfor %}
            <!--
            <a href="#" target="_blank" class="deg0 circle-fa" id="twitter"><i
                    class="fab fa-twitter icon-fa"></i></a>
            <a href="https://github.com/FabianVolkers" id="github" class="deg45 circle-fa"><i
                    class="fab fa-github icon-fa"></i></a>
            <a href="#" target="_blank" id="free-code-camp"
                class="deg90 circle-fa"><i class="fab fa-free-code-camp icon-fa"></i></a>
            <a href="#" target="_blank" id="spotify" class="deg135 circle-fa"><i class="fab fa-spotify icon-fa"></i></a>
            <a href="https://soundcloud.com/fabianvolkers" target="_blank" id="soundcloud" class="deg180 circle-fa"><i
                    class="fab fa-soundcloud icon-fa"></i></a>
            <a href="#" target="_blank" id="youtube"
                class="deg225 circle-fa"><i class="fab fa-youtube icon-fa"></i></a>
            <a href="https://www.linkedin.com/in/fabianvolkers/" id="linkedin"
                class="deg270 circle-fa"><i class="fab fa-linkedin-in icon-fa"></i></a>
            <a href="https://blog.fabianvolkers.com" id="blog" class="deg315 circle-fa"><i
                    class="fas fa-blog"></i></a>
-->
        </div>
    </div>
</div>

homepage/portfolio/templates/portfolio/section_spotlight.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<div class="spotlight-container">
    {% for spotlight in collectionitems %}
    {% if spotlight.common.spotlight == True %}
    <img src='{{ MEDIA_URL }}{{ spotlight.common.image }}' draggable="false" class="spotlight-img"
        alt-text="{{ spotlight.image_alttext }}">
    {% for item_section in sections %}
    {% if item_section.common.id == spotlight.common.parent_section.id %}
    <a href="{% url spotlight.common.detail_view item_section.slug spotlight.slug %}">
        <span class="spotlight-caption">{{ spotlight.name }}</span>
    </a>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endfor %}
    <span class="button-left" onclick="plusDivs(-1)">&#10094;</span>
    <span class="button-right" onclick="plusDivs(+1)">&#10095;</span>
    <div class="spotlight-indicator-container">
        {% for spotlight in collectionitems %}
        {% if spotlight.common.spotlight == True %}
        <span class="indicator-transparent spotlight-indicator" onclick="currentDiv({{ forloop.counter }})"></span>
        {% endif %}
        {% endfor %}
    </div>
</div>

homepage/portfolio/templates/portfolio/unconfirmed_email.html.jinja2
Please confirm your email before sending more messages.
<br>
<form action="{% url 'portfolio:send-confirmation-email' contact.id %}" method="post">
{% csrf_token %}
<input type='hidden' value='{{ contact.email_address }}'></input>
<input type='submit' value="Resend confirmation email">
</form>